=== portnoyslp/qualm/qualm.dtd
<!ELEMENT qualm-data (title?,midi-channels, patches,
	  default-trigger?, reverse-trigger?, setup-events?, cue+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT midi-channels (channel+)>
<!ELEMENT channel (#PCDATA)>
<!ATTLIST channel 
	  num CDATA #REQUIRED>
<!--
     <midi-channels>
       <channel num="1">Main Keyboard</channel>
       <channel num="2">Auxiliary Keyboard</channel>
       <channel num="10">Drum Kit</channel>
     </midi-channels>
-->
<!ELEMENT patches (patch+)>
<!ELEMENT patch (#PCDATA)>
<!ATTLIST patch 
	  num CDATA #REQUIRED
	  channel CDATA #IMPLIED>
<!--
     <patches>
       <patch num="1">Nice Piano</patch>
       <patch num="2">TremStr/Str</patch>
       <patch num="5">Organ</patch>
     </patches>
-->

<!ELEMENT default-trigger (trigger)>
<!ELEMENT reverse-trigger (trigger)>
<!ELEMENT setup-events (event+)>

<!ELEMENT cue (trigger?, event+)>
<!ATTLIST cue song CDATA #REQUIRED measure CDATA #REQUIRED>
<!ELEMENT trigger (note-on|note-off|control-change|clear)>
<!ATTLIST trigger
	  delay CDATA #IMPLIED>
<!ELEMENT note-on EMPTY>
<!ATTLIST note-on 
	  channel CDATA #REQUIRED
	  note CDATA #REQUIRED>
<!ELEMENT note-off EMPTY>
<!ATTLIST note-off 
	  channel CDATA #REQUIRED 
	  note CDATA #REQUIRED>
<!ELEMENT control-change EMPTY>
<!ATTLIST control-change
	  channel CDATA #REQUIRED
	  control CDATA #REQUIRED
	  threshold CDATA #REQUIRED>
<!ELEMENT clear EMPTY>
<!ATTLIST clear 
	  channel CDATA #REQUIRED 
	  duration CDATA #REQUIRED>

<!ELEMENT event (program-change)>
<!ELEMENT program-change EMPTY>
<!ATTLIST program-change
	  channel CDATA #REQUIRED 
	  patch CDATA #REQUIRED>

=== portnoyslp/qualm/batboy-k2.xml
<?xml version="1.0"?>
<!DOCTYPE qualm-data SYSTEM "qualm.dtd">
<qualm-data>
  <title>Bat Boy Keyboard II</title>
  <midi-channels>
    <channel num="1">Main Keyboard</channel>
    <channel num="2">Auxiliary Keyboard</channel>
    <channel num="10">Drum Kit</channel>
  </midi-channels>
  <patches>
    <patch num="1">Nice Piano</patch>
    <patch num="2">TremStr/Str</patch>
    <patch num="3">FuzzClav/Str</patch>
    <patch num="4">Rhodes</patch>
    <patch num="5">Organ</patch>
  </patches>
  <default-trigger><trigger><foot channel="1"/></trigger></default-trigger>
  <reverse-trigger>
    <trigger><note-on channel="1" note="c-1"/></trigger>
  </reverse-trigger>
  <setup-events>
    <event><program-change channel="1" patch="1"/></event>
    <event><program-change channel="2" patch="5"/></event>
  </setup-events>

  <cue song="1a" measure="10">
    <trigger><note-on channel="1" note="C4"/></trigger>
    <event><program-change channel="1" patch="3"/></event>
  </cue>
  <cue song="2" measure="17">
    <event><program-change channel="1" patch="4"/></event>
  </cue>
</qualm-data>
